### ISSUE TITLE
post hook problem with Async serial middleware

### ISSUE THREAD

**Issue by ChitaGideon** [keystonejs/grappling-hook#11]
```
var grappling, instance;

grappling = require('grappling-hook');

instance = grappling.create();

instance.addHooks({
  save: function(done) {
    console.log('save!');
    done();
  }
});

instance.pre('save', function(next) {
  console.log('saving!');
 next("saving")
}).post('save', function() {
  console.log('saved!');    //this post hook never be called
});

instance.save(function(err) {
  console.log('All done!!');
});
```

anything I miss?

**Comment by creynders** [comment]
Yes, the callbacks are nodestyle, i.e. they expect an error object as first parameter. So, when you pass "saving" to `next`, it's treated as an error and execution is immediately halted. If you add `console.log(err)` to the finale callback, it'll output "saving"

**Comment by ChitaGideon** [comment]
ok.
If I use async serial middleware ,in  some pre callback I validate something  and never call `next` function again in order to forbid  original function calling
Never call `next` function ,would that lead to be any memory problem ？

**Comment by ChitaGideon** [comment]
And,is there any possiblity to access (even manage) the arguments that pass to the original function

**Comment by creynders** [comment]
> If I use async serial middleware ,in some pre callback I validate something and never call next function again in order to forbid original function calling

No. If you want to prevent the original function from being called you need to pass an error object in your 'pre' middleware to `next` as the first argument. `next` should _always_ be called.

E.g.:

``` js
instance.pre('save', function(next){
  //do some validation, oh no we have to prevent the save
  next(new Error('NO SAVING BUDDY!'));
});

instance.save(function(err){
  if(err){
    console.log(err)
  }
});

//outputs:
//Error: NO SAVING BUDDY!
```

> is there any possiblity to access (even manage) the arguments that pass to the original function

Yes, any parameters passed to the original function will be passed to the middleware too. E.g.:

``` js
instance.pre('save', function(a, b, c, next){
  console.log(a, b, c);
  next();
});

instance.save('here', 'we', 'go', function(){
  console.log('done');
});

//outputs:
//here we go
//done
```

You cannot manipulate the parameters inside middleware though. This will probably be added later on, but I haven't decided upon the API to do so yet.

**Comment by ChitaGideon** [comment]
Many thanks for your fast and detailed reply.
I try to use your example ,and I still got some problem

```
grappling = require('grappling-hook');


 instance = {
    save : function(a,b,done){
        console.log('save!',a,b);
        done && done();
    }
};

grappling.mixin(instance); // add grappling-hook functionality to an existing object

instance.addHooks('save'); // setup hooking for an existing method

instance.pre('save', function(a,b,next){
    console.log('saving!',arguments);
    next()
}).post('save', function(){
    console.log('saved!');
});
//instance.callHook('pre:save', 1, "b",function (){
  //console.log("callHook",arguments);
//});
instance.save(1,"b",function (){
  console.log("done!",arguments)
});
```

  `callHook`  can pass parameter correctly.  But when I try to call `save` function ,an error occurred

```
TypeError: undefined is not a function
  at Object.<anonymous> (...indexMain.js:22:5)
  at async.eachSeries.asyncFinished (...node_modules/grappling-hook/index.js:110:14)
  at iterate (...node_modules/grappling-hook/node_modules/async/lib/async.js:146:13)
  at Object.async.eachSeries (...node_modules/grappling-hook/node_modules/async/lib/async.js:162:9)
  at iterateAsyncMiddleware (...node_modules/grappling-hook/index.js:99:8)
  at dezalgo (...node_modules/grappling-hook/index.js:66:11)
  at Object.instance.(anonymous function) [as save] (...node_modules/grappling-hook/index.js:156:5)
  at Object.<anonymous> (...indexMain.js:30:10)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)

```

**Comment by creynders** [comment]
Ouch, that's a legit bug I think. Need to verify.

**Comment by ChitaGideon** [comment]
I am little bit confused about  usage scenario of `attach`
Obviously,`attack` to a class is awesome ,and really helpful in some OOP situation. I just can not figure out why should step hooking on instance level ，rather than class level.
The example shows

```
grappling.attach(Clazz); // attach grappling-hook functionality to a 'class'
var instance = new Clazz();
instance.addHooks('save'); // setup hooking for an existing method
```

If I have already ability to access the the instance , I just need `mixin` it.

```
grappling.mixin(instance); // add grappling-hook functionality to an existing object
instance.addHooks('save'); // setup hooking for an existing method
```

Thus, I consider  that after `attach` a class , hook can be setupped on class would be more useful.

**Comment by creynders** [comment]
Sure, but sometimes you want to add hooking to an instance coming from a third party module for instance, i.e. where you can't access the prototype. We just wanted to provide multiple ways to use grappling hook.

**Comment by creynders** [comment]
@ChitaGideon FYI: I updated all examples and wrote separate tests for them, i.e. now the documentation should definitely be correct :grin: 
Thanks for reporting this!
