### ISSUE TITLE
Issue with `keystone.pre('routes', middleware)`

### ISSUE THREAD

**Issue by sendyhalim** [keystonejs/grappling-hook#13]
Hi there, I want to report (possible) a bug.

inside `/index.js` line 206 method `iterateAsyncMiddleware`:

```
    async.eachSeries(middleware, function(callback, next) {
        var d = callback.length - args.length;
        switch (d) {
            case 1: //async series
                callback.apply(context, args.concat(next));
                break;
            case 2: //async parallel
                callback.apply(context, args.concat(next, wait(callback)));
                break;
            default :
                //synced
                var err;
                var result;
                try {
                    result = callback.apply(context, args);
                } catch (e) {
                    err = e;
                }
                if (!err && module.exports.isThenable(result)) {
                    //thenable
                    result.then(function() {
                        next();
                    }, next);
                } else {
                    //synced
                    next(err);
                }
        }
    }, function(err) {
```

`var d = callback.length - args.length;` will not pass `next` to `callback` (middleware) if I register pre routes hook like this:

```
keystone.pre('routes', function () {
  return someMiddleware.apply(null, arguments);
});
```

This happens because there's a 3rd party libraries that use coffeescript. (I'm using asset-rack)
the converted(from coffeescript to javascript) function (middleware) is as follows

```
function () {
  fn.apply(me, arguments);
}
```

`callback.length` will have value 0, and it will go to the `default` switch case and won't get the async `next` callback.

**Comment by creynders** [comment]
The problem is that `grappling-hook` somehow needs to know how to treat the middleware function: async or sync.
So a solution for now would be to wrap your 3rd party middleware with a function declaring the necessary parameters:

``` js
keystone.pre('routes', function(req, res, next){
    return someMiddleware.apply(null, arguments);
});
```

Another solution would be that I bypass `grappling-hook` middleware handling altogether for keystone's `pre:routes`, but I need to check that with @JedWatson and think it through. The downside of that approach is that it reduces the flexibility of `pre:routes`. ATM it benefits from what `grappling-hook` offers: the possibility to use synced and thenable middleware too.

**Comment by creynders** [comment]
Come to think of it, two other solutions exist too:

1/ marking a middleware as async, something like:

``` js
var someMiddleware = thirdpartylib.createMiddleware();
someMiddleware.async = true;
keystone.pre('routes', someMiddleware);
```

2/ Force `grappling-hook` to handle middleware as async, even if the function signature doesn't match. I.e. a sort of "I know what I'm doing, leave me the fuck alone"-method

``` js
keystone.preAsync('routes', someMiddleware);
```

I think I like the last one.

**Comment by sendyhalim** [comment]
Actually I did the first solution, which is to wrap the middleware explicitly with 3 parameters. 

```
keystone.pre('routes', function (req, res, next) {
  return thirdPartyLib.someMiddleware(req, res, next);
});
```

Anyway thanks for the quick response! I'm closing this.

**Comment by JedWatson** [comment]
FYI I pushed a new release yesterday that updates the way you can hook into middleware. Some events (from our own projects) need to be able to define path-specific middleware, which the `trapping-hook` implementation doesn't facilitate.

I've now added several Keystone options that mirror the hooks for "advanced" usage, see keystonejs/keystone#1736
