### ISSUE TITLE
Allow for filter hooks

### ISSUE THREAD

**Issue by mattapperson** [keystonejs/grappling-hook#14]
I would like to suggest an additional type of hook, a filter hook.
### Rational:

Plugins should be able to effect change within other plugins or core itself. I would state that I think the ability to have filter hooks has been a major contributor to word presses success as It allows a system to be far more flexible.
### Use-case:

For example, word presses query filters:

``` php
function exclude_category( $query ) {
    if ( $query->is_home() && $query->is_main_query() ) {
        $query->set( 'cat', '-1,-1347' );
    }
}
add_action( 'pre_get_posts', 'exclude_category' );
```

In the above case, a plugin can filter the results a user sees.

**Comment by creynders** [comment]
Hey @mattapperson 

I think I misunderstand what you're trying to do here, since to me it seems this is already possible?
In the above example you simply act on the passed object, which is no different in javascript. E.g.

``` js
function foo(q, next){
   q.foo = 'FOO';
   next()
}
function fooLog(q, next){
  console.log(q.foo);
  next();
}

instance.pre('baz', foo, fooLog);
instance.callHook('pre:baz', {}); //outputs: FOO
```

**Comment by mattapperson** [comment]
@creynders you are incorrect. I'm my code, if you add that to a plugin you change how the homepage filters content. You are literally injecting a filter into your app and changing how it functions. This is not a simple action hook as keystone currently supports

**Comment by mattapperson** [comment]
@creynders fwiw almost all major cms systems support this concept of filter hooks.

**Comment by creynders** [comment]
@mattapperson I think there's a little confusion on what `grappling-hook` does exactly and its relation to keystone. Grappling-hook simply provides a hooking mechanism, which is used by hook providers to create a hooking API. Hook consumers can respond to these with middleware, which are injected with whatever parameters the hook provider passes through.

I.e. if you want to manipulate filtering from hook middleware, the hook provider - keystone in this case - needs to pass a parameter which allows you to do so. If that's what you're really after, then it's best to open an issue in the keystone repo. Or maybe we're still misunderstanding each other :grin:

**Comment by mattapperson** [comment]
I think we are sort of on the same page. I just feel that this should be done on the hook level with a defined API for manipulating content of the hooked code by middleware rather then making that an implementation detail
