### ISSUE TITLE
Support for methods that return a promise

### ISSUE THREAD

**Issue by estilles** [keystonejs/grappling-hook#5]
First, @creynders and @JedWatson this is an AWESOME hooks implementation. I've been using using [kareem](https://github.com/vkarpov15/kareem) ever since hooks became unsupported, but I'm going to migrate all my apps to grappling. This implementation is "off-the-hook". :-)

Enough compliments, now back to business.

I ran into a use-case recently (might be a bit of an edge case) in which I needed to support pre/post hooks for a method that returned a promise. My initial workaround was simply to wrap the method in an async function with a callback upon resolution. While this works fine, I've been encountering this use-case more frequently, so I was considered submitting a PR to kareem to support this.

Now that I'm switching to grappling, I'm wondering if you're inclined to support this feature.

Thanks again for sharing this! It is, by far, the best hooks implementation I've seen.

**Comment by creynders** [comment]
Wow, so much praise makes me :blush: 
I definitely want to have some promise integration in `grappling-hook`, in fact I already started to sketch out a few ideas, but will need to revisit those now that middleware iteration internals have changed substantially.
I'd love to accept promises both in `pre` and `post` but also in `callHook`. 

Definitely :+1:

**Comment by estilles** [comment]
@creynders, I'm happy to hear (read) that you're onboard with this. I'm gone through your most recent codebase and the new middleware iteration (genius, BTW) makes this feature a lot easier to implement. 

I'm looking forward to see what you come up with. If you need a extra set of hands or eyes, I'm more than willing to pitch in.

**Comment by creynders** [comment]
Reminder to self: figure out what to do with hook-wrapped methods that return promises. Might be a tough one to crack.

**Comment by creynders** [comment]
So, this is what we want to achieve, right @JohnnyEstilles ?

```
//add middleware
instance.pre('test', fnReturningPromise); //queue finishes once returned promise is resolved

//executing middleware
instance.callHook('pre:test', promise); //once queue finishes promise will be resolved

//'save' is a wrapped method, which returns a promise
instance.save().then(...); // then is executed once all pre middleware has finished, the original 'save' has executed and all post middleware has finished.
```

**Comment by creynders** [comment]
Hmmm, the second is already covered, come to think of it:

```js
instance.callHook('pre:test', promise.resolve);
```

**Comment by estilles** [comment]
Yes! That's exactly what I envisioned. :-) I couldn't have articulated it any better.

**Comment by creynders** [comment]
@JohnnyEstilles do you have a lot of experience with various promise libs? Thing is: I really can't avoid constructing a promise manually, but obviously this ties me down to a specific implementation, which I _really_ would like to avoid.
I'm thinking of accepting some kind of `factory` function through `options` which would be used to create the promises I need. For instance: a function which injects a function with `resolve` and `reject` functions as parameters. Sth like:

``` js
grappling.create({
  promise: function(f){
    return new P(f);
  }
});
```

The above would be usable as-is with `bluebird` for instance.

**Comment by estilles** [comment]
I assumed from the get-go you were going to use a BYO "A+ compatible" promise lib strategy, defaulting to the lib of your choice (I'm a fan of bluebird). So, your idea of accepting a factory is spot on.

**Comment by creynders** [comment]
Hey @JohnnyEstilles I pushed a promises branch, have a look. In a nut shell:

You can use promise returning middleware with `pre`, `post` and `hook` for async hooks. You can wrap methods that return promises through `addPromisedHooks` and call a hook returning a promise with `callPromisedHook`

**Comment by creynders** [comment]
:rocket:
