### ISSUE TITLE
Edge-case support: Treat hook as sync even when last arg is not passed

### ISSUE THREAD

**Issue by estilles** [keystonejs/grappling-hook#7]
@creynders, I'm not sure if you're willing to support this, but I ran into a weird edge-case. This is the scenario:

``` js
var instance = {
  // "method" is SYNC, "fn" is NOT a callback
  method: function(fn) { // <-- grappling assumes this is ASYNC when arg not passed
    if('function' === typeof fn) {
       ... do something with fn
    }
  }
}

grappling.mixin(instance)
  .addHooks('method')
  .pre('method', function() {
    ... do something
  });

instance.method(); 
```

Since the `fn` is not passed to `instance.method()` <del>last parameter (`fn`) is a `function`</del> grappling assumes `.method()` is async.<del>, when in this particular case it's not.</del>

Would you be willing to support this edge-case? Maybe with an `.addHooksSync()` method or something similar ...

**Comment by creynders** [comment]
Hmmm, weird, _if_ I understand your use case _and_ I'm not mistaken, this _should_ work. Obviously if it doesn't it's  bug. But grappling does NOT assume that if the last parameter is a function it's async by default, only if the middleware function accepts one parameter more than the number of arguments passed.
I'll look into it whether it's a bug or not.

**Comment by estilles** [comment]
I think this needs further explanation ...

The method I'm mixing in grappling is an object from a third-party method. The instance in which I ran into an issue `.method()` was called without an argument. `.method()` internally checked for the missing argument.

**Comment by estilles** [comment]
So ... you have no bug. It works as advertised. Let me know if you're willing to support this edge-case, otherwise I'm sure I can find a workaround.

**Comment by estilles** [comment]
I updated my original comment to show to actual edge-case.

**Comment by creynders** [comment]
Ok, I get it. Yes, it's explicitly assumed that wrapped methods are asynchronous, but I must confess I never thought about wrapping 3rd party methods that may or may not be async. I'll think on it. I try to keep the API as clean/simple as possible, but on the other hand, maybe this is a more common use case than we think.

Obviously the solution for the time being is to manually wrap the method:

``` js
instance._method = instance.method;
instance.method = function(fn){
  instance.callHook('pre:method', function(err){
    instance._method(fn);
    instance.callHook('post:method');
  });
}
```

**Comment by estilles** [comment]
That's exactly what I'm doing right now. :-)

**Comment by creynders** [comment]
I've been thinking about this, but I can't come up with a good solution. The problem is that the full stack gets dezalgofied, which means it'll _always_ finish async. If I would add a `addSyncHooks` method it seems to me that people would expect the wrapped method to still operate sync, i.e. you could return a value from the wrapped method, but that's simply impossible (w/o dropping the dezalgofication)

When comparing to `hooks` and `kareem`, they seem to have the same "problem". Aarrgh... this sync/async stuff gives me headaches :grin:

**Comment by creynders** [comment]
Another problem is that if I'd drop the dezalgofication for syncHooks it would open the door for very hard to find bugs. E.g. 

``` js
instance.syncMethod = function(foo){
  return foo;
}
instance.addSyncHooks('syncMethod');
```

This works:

``` js
console.log(instance.syncMethod('foo'));
```

```
# outputs
foo
```

This too:

``` js
instance.pre('syncMethod', function(){
  console.log('sync PRE');
});
console.log(instance.syncMethod('bar'));
```

```
# outputs
sync PRE
bar
```

But then...

``` js
instance.pre('syncMethod', function(next){
  console.log('async PRE');
  next();
});
console.log(instance.syncMethod('qux'));
```

```
# outputs
async PRE
undefined
```

:bomb: 

So, another step down the ever deepening rabbit hole would mean that... only sync middleware is allowed? Any middleware is allowed, but it's run sync? Or...?

**Comment by creynders** [comment]
Ok, got it all figured out.

**Comment by estilles** [comment]
I'm waiting with bated breath ... :-)
