### ISSUE TITLE
Exception black-hole

### ISSUE THREAD

**Issue by estilles** [keystonejs/grappling-hook#8]
Is it just me or are some exceptions disappearing into a black-hole vortex? :-)

**Comment by creynders** [comment]
Ouch. Any pointers in which situations?

**Comment by estilles** [comment]
It's happened to me in a few scenarios so far. The following describes the most recent:
- running two instances of grappling (let's call them instance A and B)
- both mixed-in to existing objects
- a call to a method in instance A kicks off a hook cycle
- within the `post` hook of the instance A method a call to a hooked method in instance B kicks off another cycle
- an exception occurs in the in the `pre` hook of the instance B method
- both instances return from their respective cycles
- pending succesive hooks in both instances do not get called 
- no error is thrown
- the application continues ...

Since I used `instance.addHooks('name')` in both instances to add hooks to existing methods, I didn't have any callbacks to check for errors. I was expecting a exception to be thrown.

Hooks from one instance being invoked from a hook in another instance if probably somewhat of an edge-case, but I couldn't think of any reason why it wouldn't work.

Still trying to figure out if I did something wrong.

**Comment by creynders** [comment]
Those are sync methods right? By default errors thworn in sync methods are caught and passed to the callback. Only a few days ago I realised this is incorrect behaviour. I'll push the fix to master, but won't release it yet. I really want to think this through. But maybe you can use the `master` version for now, to see if it solves your problem.

**Comment by creynders** [comment]
Pushed to `master`

**Comment by estilles** [comment]
Yes. They are all sync methods. Will test tomorrow using master, after the Pacquiao v. Mayweather fight. :-)

**Comment by creynders** [comment]
@JohnnyEstilles had some time to test this? I'm going to merge the fix in, since it really doesn't make sense to catch the errors in sync methods.
Closing this, but let me know if you encounter any more troubles.

**Comment by estilles** [comment]
My apologies for not getting back to you. The changes worked well in my use cases. Glad to see your merging. Publishing to `npm` soon?

**Comment by creynders** [comment]
Wow, that's fast :grin: Yeah, cutting a release today.

**Comment by creynders** [comment]
:trumpet: `v2.2.0`

**Comment by estilles** [comment]
Yeah, I was, coincidentally, right in the middle of testing when I say you comment! :-)

**Comment by estilles** [comment]
That's awesome! Thanks for releasing so fast.

**Comment by creynders** [comment]
Argh, totally forgot I wanted to squeeze in another change: using other qualifiers than `pre` and `post`.
_sigh_ `v2.3.0` it is then...
